// Pre-build script for Vercel API function
// Bundles server/api-handler.ts + all server code into api/index.js
import { build } from "esbuild";

async function buildApi() {
  console.log("Building API bundle for Vercel...");
  
  await build({
    entryPoints: ["server/api-handler.ts"],
    platform: "node",
    bundle: true,
    format: "esm",
    outfile: "api/index.js",
    target: "node18",
    minify: false,
    external: [
      // Keep native/large modules external — Vercel resolves from node_modules
      "@libsql/client",
      "express",
      "multer",
      "drizzle-orm",
      "drizzle-orm/libsql",
      "openai",
      "pdfjs-dist",
      "@napi-rs/canvas",
      "dotenv",
      "dotenv/config",
    ],
    logLevel: "info",
    banner: {
      js: '// Auto-generated by script/build-api.ts — do not edit manually',
    },
  });

  console.log("API bundle built successfully → api/index.js");
}

buildApi().catch((err) => {
  console.error("Build failed:", err);
  process.exit(1);
});
